insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('crosenzveig0', 'Rolfson-Dickens');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmacmillan1', 'Borer-Maggio');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('amenichini2', 'Moen, Nicolas and Paucek');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jfrawley3', 'Reilly, Bode and Simonis');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('abakesef4', 'Spencer, Blanda and Bode');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('grattenberie5', 'Hand-Grant');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('psegeswoeth6', 'McLaughlin, Pouros and Walsh');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rportress7', 'Ondricka LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smcpake8', 'Lubowitz, Gottlieb and Flatley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hpiesold9', 'Haley and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ccahillanea', 'Mueller, Heidenreich and Cassin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bgristb', 'Yundt Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pelamc', 'Reichert Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bkayleyd', 'Nikolaus, Roob and Swift');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ajeevese', 'Mayer and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('msprowsonf', 'Russel and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gbramfordg', 'Crist, Fadel and Vandervort');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('shumphrysh', 'Kerluke-Jenkins');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('awoodruffi', 'Kub-Rosenbaum');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fcraythornej', 'Wilkinson, Stroman and Haley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dduckhamk', 'Predovic LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('evermanl', 'Fadel, Metz and Strosin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ejaffam', 'Rempel Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mliggettn', 'Kuvalis-Waters');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bsquibbeso', 'Rosenbaum LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ngrigoriscup', 'Lubowitz LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bboylandq', 'Jerde, Boyer and Smitham');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('abeviller', 'Lesch, Ledner and Prosacco');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hbamburys', 'Cartwright-Thiel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kgallehawkt', 'Brakus, Torphy and Lockman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dblockeyu', 'Windler-Beer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('espinckev', 'Braun and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sgourleyw', 'Kling-Mayer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sduffyx', 'Beatty-Hettinger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hfearsy', 'Rutherford-Haley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ihulcoopz', 'Lockman Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('oschleswigholstein10', 'Ledner and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ihaburne11', 'Klein and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ygamlen12', 'Brekke-Kulas');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mallsworth13', 'Grady LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('codea14', 'Parisian LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('isterre15', 'Will-Flatley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hmateev16', 'Kris-Balistreri');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zomahony17', 'Lemke-Rogahn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ablanko18', 'Weber-O''Reilly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wpigney19', 'Stark, Lindgren and Bergstrom');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('foliphard1a', 'Hartmann, Lubowitz and Pagac');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ibenardeau1b', 'Rodriguez Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ctest1c', 'Dare-Stamm');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eyarnall1d', 'Pollich Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jaccombe1e', 'Connelly-Quigley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('shan1f', 'VonRueden LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tmacardle1g', 'Wisoky-Sanford');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gvogelein1h', 'Streich Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lvickarman1i', 'Green-Schaefer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eharbour1j', 'Marks and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('phallmark1k', 'Schamberger-Kuvalis');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bbrowse1l', 'Harris-Pollich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aboult1m', 'Davis Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldudlestone1n', 'Fahey, Nitzsche and Ebert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dcampanelle1o', 'Cassin, Wintheiser and Torp');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dleinthall1p', 'Farrell-Bahringer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbezant1q', 'Pacocha-Anderson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pledingham1r', 'Mohr and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jpurdey1s', 'Oberbrunner-Padberg');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hsherlock1t', 'Orn, Hackett and Lynch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ewardlaw1u', 'Sanford-Gibson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rmclaren1v', 'Jones-Jones');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fbirdsey1w', 'Pfannerstill-Lesch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gwithrop1x', 'White, Treutel and Jenkins');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kbricknall1y', 'Kuhic, Denesik and Toy');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nayerst1z', 'Trantow-Effertz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zmeth20', 'Okuneva, Bartoletti and Hoppe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rgreeves21', 'Larson-Bartell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hattrey22', 'Ullrich-Brown');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lhanway23', 'Gleason, Zieme and Legros');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hcayley24', 'Monahan, Larson and Thompson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gisakson25', 'Schuster and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lglaister26', 'Gorczany Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dcuddon27', 'Trantow-McClure');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mellicombe28', 'Harris Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mjackling29', 'Ortiz LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fpaulot2a', 'Schimmel-Batz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gbrydon2b', 'Tremblay-Schultz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('creichert2c', 'Yost Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bgodspeede2d', 'McClure and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aarnaud2e', 'Trantow, Heidenreich and Yundt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cbaudino2f', 'Boehm, Simonis and Simonis');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fcurnow2g', 'Wyman Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jdegiovanni2h', 'Rice Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('twyldbore2i', 'Bechtelar, Swaniawski and Haag');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fgrcic2j', 'Leannon Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdundredge2k', 'Kub, Marvin and Wolf');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('joloman2l', 'Denesik Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wreese2m', 'Ernser-Sauer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wdorcey2n', 'Homenick, Jakubowski and Koch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ewerendell2o', 'Shields, Greenfelder and McKenzie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jofer2p', 'Botsford, Gleason and Kirlin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cferenczi2q', 'Cruickshank, DuBuque and Ondricka');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kcrotch2r', 'Jacobson Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pruprich2s', 'Grimes, Corkery and Rosenbaum');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ctorra2t', 'Leannon, Wyman and Koelpin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cbirds2u', 'Turner Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ploram2v', 'West and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('evidler2w', 'Wolf, Shields and Tromp');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dfibbens2x', 'Terry, Mills and Mosciski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmarcam2y', 'Sipes Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('omarchenko2z', 'Konopelski, Kovacek and Hahn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aoseman30', 'Swift and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hbaiss31', 'Greenfelder, Jerde and Buckridge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jhallas32', 'Willms, Walter and Boyle');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('csimonson33', 'Rutherford-Kub');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('emackellar34', 'Kertzmann Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dgreatbanks35', 'Robel, Padberg and Schultz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmattecot36', 'Kub Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ntidmarsh37', 'Brakus-Halvorson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dbrickner38', 'Flatley Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jblunsen39', 'Ernser and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ksanto3a', 'Maggio, Leannon and Emard');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nfurby3b', 'Balistreri and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mjockle3c', 'Luettgen, Corwin and Schaefer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fmccool3d', 'Corwin-Schowalter');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ssaggers3e', 'Williamson-Fritsch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lfitchett3f', 'Leannon, Wilkinson and Kassulke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mribbens3g', 'Botsford Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mtulloch3h', 'Kub Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ksharple3i', 'Gaylord and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('goshee3j', 'Eichmann LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jday3k', 'Gutkowski-Kertzmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sbrims3l', 'Kuphal-Dibbert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('brideout3m', 'Simonis Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aorourke3n', 'Parker-White');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hpachmann3o', 'Macejkovic LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rpeeter3p', 'Leuschke, Breitenberg and Spinka');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('amuldoon3q', 'Gleason-Rowe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rgrigsby3r', 'Schuppe Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fsurby3s', 'Fahey, Schroeder and Armstrong');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mhudel3t', 'Fadel-Bartell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kseeviour3u', 'Kub Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('egrishkov3v', 'Mann, Champlin and Breitenberg');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('caicheson3w', 'Daniel Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbird3x', 'Gusikowski and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gduggen3y', 'Balistreri, Labadie and Casper');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('llindenbluth3z', 'Miller-Williamson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jnulty40', 'Klein and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('llongbothom41', 'Rodriguez and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wcristoferi42', 'Rice, Conroy and Murray');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('otrathen43', 'Hartmann Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahatliff44', 'Dickens, Nienow and Conroy');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbenedek45', 'Welch-Cremin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('flawson46', 'Gottlieb-Kunde');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tattwoull47', 'Mosciski-Hammes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('slannon48', 'Stamm LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sdavids49', 'Wiza-Pouros');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('egillian4a', 'Jerde Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('elie4b', 'Bartell-Volkman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mbagwell4c', 'Gorczany and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tmowles4d', 'Koch LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('scloney4e', 'Champlin LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pduchatel4f', 'Ondricka, Effertz and Rowe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldulwich4g', 'Zemlak Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lkingsman4h', 'Abshire, Howell and Bednar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kmullender4i', 'Herman, Hansen and Kilback');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pbeynon4j', 'Macejkovic and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('llailey4k', 'Howell Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sblackstone4l', 'Wolff-Oberbrunner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('blamasna4m', 'Volkman and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('meckersley4n', 'D''Amore, Tromp and Schinner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mabbots4o', 'Grimes, Schaefer and Prosacco');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gfairnington4p', 'Douglas LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ljozwicki4q', 'Bergstrom and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fcroker4r', 'Grant LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cphilott4s', 'Schroeder-Rogahn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sgarden4t', 'Smitham-Greenholt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dpickles4u', 'Bins-Kiehn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rdarnell4v', 'Gulgowski, Altenwerth and Brekke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('palvis4w', 'Lebsack LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('caberdein4x', 'Tremblay Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hbolt4y', 'Davis, Feil and Johnston');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gripping4z', 'Batz, Kling and Muller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dcorbyn50', 'Goodwin, Moore and Reichert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ljeynes51', 'Cormier and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bbrandi52', 'Walker and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mcargen53', 'Okuneva LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('esimmank54', 'Upton Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rgalilee55', 'Cartwright-Jakubowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nbysshe56', 'Kutch Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jcorter57', 'Bahringer-McCullough');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kworvell58', 'Orn, Krajcik and Berge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('skahn59', 'Kreiger Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clavigne5a', 'Roberts, Zieme and Bartoletti');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tangeau5b', 'Balistreri, Nolan and Parisian');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tboar5c', 'Rosenbaum-O''Keefe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lhollerin5d', 'Muller Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fwinkell5e', 'Altenwerth-Reynolds');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('yendley5f', 'Buckridge and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vkettow5g', 'Howell-Stoltenberg');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dtrewman5h', 'Harris Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rculkin5i', 'Smitham LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eslisby5j', 'Goyette, Rutherford and Ortiz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('efrizzell5k', 'Koss-Weber');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kskeffington5l', 'Cronin Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cforsdike5m', 'Schmeler and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ieisikovitsh5n', 'White LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bpierson5o', 'Nolan, Lueilwitz and Bogan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sflexman5p', 'Connelly and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bcoutts5q', 'Hand-Ankunding');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ctarply5r', 'Mertz-Leuschke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bstandbrooke5s', 'Douglas and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('levers5t', 'Schneider-Schinner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dpedrocco5u', 'Witting Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmaruska5v', 'Schmidt, Hane and Kuphal');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gedgerton5w', 'Monahan, Jakubowski and Halvorson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('osacher5x', 'Collins Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wpryer5y', 'Terry Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sshearme5z', 'Klocko LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ckeenor60', 'Reichert-Zulauf');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dfigiovanni61', 'Legros-Boehm');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jwarde62', 'Hammes and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bcleland63', 'Kassulke-Hagenes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmerrell64', 'Gleason-Will');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ucutridge65', 'Pagac-Zemlak');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kgrinyer66', 'Tillman, Stamm and Mueller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dmccurdy67', 'Feeney and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('iitzcak68', 'Greenfelder-Bergnaum');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jreuther69', 'Kshlerin-Predovic');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mgrimshaw6a', 'Keeling, Conroy and Mohr');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tdanielczyk6b', 'Goldner-Metz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hmussilli6c', 'King, Becker and Lind');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rwaslin6d', 'Durgan, Mitchell and Legros');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('seaden6e', 'Wolf-Block');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('esandcraft6f', 'Tillman-O''Connell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hfillary6g', 'Tromp-Orn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bgautrey6h', 'Kozey LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('iparkes6i', 'Smith, McGlynn and O''Connell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bjosskovitz6j', 'Gusikowski, Mohr and Borer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lwinkworth6k', 'Larkin-Kirlin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('slutas6l', 'Effertz and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ljurgen6m', 'Fisher, Strosin and Lesch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hianson6n', 'Goyette Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mreston6o', 'McClure Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mpyett6p', 'Tillman-Cassin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dguichard6q', 'Kertzmann, Watsica and Lueilwitz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jconstance6r', 'Swaniawski, Aufderhar and Kunde');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wtribbeck6s', 'Botsford LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dmilesap6t', 'O''Conner, Will and Howe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lseals6u', 'Cole, Casper and Bartell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gbolletti6v', 'Hegmann-Windler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mmorrel6w', 'White, Koepp and Kilback');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dstarr6x', 'Hoeger Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zdarnbrook6y', 'Terry-Gutmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbrittain6z', 'Rowe Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('agoodinge70', 'Weber Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hllywarch71', 'Kerluke-D''Amore');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nmcane72', 'Kozey-Reichel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('doswald73', 'Beatty-Wyman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbushill74', 'Quigley-Huels');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('haustins75', 'Moen, Reilly and Prohaska');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smuzzillo76', 'Breitenberg LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rlawie77', 'Nader LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmuscott78', 'Beatty-Wilkinson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nnaris79', 'Bednar, Quigley and Sanford');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nmatessian7a', 'Walsh-Lubowitz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cattwoul7b', 'Larson, Rogahn and Goyette');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aughini7c', 'Gibson, Kautzer and Reinger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ctownby7d', 'Metz-Willms');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sromaines7e', 'Denesik-Pollich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('acoward7f', 'Hegmann, Mertz and Mann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vanstee7g', 'Howell, Heaney and Davis');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lbigadike7h', 'Runte Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jbrockwell7i', 'Rolfson and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jchellam7j', 'O''Connell, Runte and Schroeder');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('valford7k', 'Leannon-Treutel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dfeld7l', 'Cummings-Hirthe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clepage7m', 'Parisian Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adymond7n', 'Keeling LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dcreegan7o', 'Gerhold Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ftwells7p', 'MacGyver, Emmerich and Bruen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ltenniswood7q', 'VonRueden-Rodriguez');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('trymmer7r', 'Labadie, Jacobson and Emmerich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hbaldick7s', 'Deckow, Anderson and Reinger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('posbiston7t', 'Corwin, Purdy and Jacobson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vruilton7u', 'Medhurst-Deckow');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rsambrook7v', 'McDermott-Turner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cbisacre7w', 'Cormier-O''Connell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('plandrick7x', 'Jaskolski-Zemlak');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kskipper7y', 'Howe Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fhandforth7z', 'Johns, Schowalter and Denesik');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smussetti80', 'Runolfsdottir, Rice and Turcotte');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mgreenrodd81', 'Keeling, Daniel and Glover');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kduckerin82', 'Bahringer-Connelly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dfear83', 'Toy, Halvorson and Daugherty');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mharnett84', 'Bruen, Schmeler and Schuster');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cshoveller85', 'Shields, Halvorson and Lesch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('barnley86', 'Welch-Schmitt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('iarington87', 'Toy LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mansett88', 'Predovic, Anderson and Hyatt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('igieves89', 'Cronin-Okuneva');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jwoodroofe8a', 'Howell-Nader');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dmainds8b', 'Nitzsche-Kilback');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dallen8c', 'Gibson, Pfeffer and Reichel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('glawrey8d', 'Lockman, Wilderman and Cole');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gbinyon8e', 'Kuphal, Beer and Cormier');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sjustun8f', 'Pouros, Lowe and Roob');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('skittel8g', 'Murazik-Pollich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('osturror8h', 'Boehm and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tdigiorgio8i', 'Erdman-Herman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lfeatonby8j', 'Harber Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ewhittenbury8k', 'Feest, Funk and Tillman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hmanuello8l', 'Dach, Ondricka and Luettgen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kgrunbaum8m', 'Swaniawski-Kling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aholborn8n', 'Gibson and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gboshers8o', 'Reilly, Connelly and Bayer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbache8p', 'Simonis Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cpiotr8q', 'King Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gstonebridge8r', 'Franecki-Gerlach');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sdumbarton8s', 'White and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('arothon8t', 'Carter LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mbirds8u', 'Langworth Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jgrzegorek8v', 'Fisher and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vsoutherton8w', 'Skiles, Kihn and Rutherford');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('glaxson8x', 'Bauch-Grady');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rgianasi8y', 'Mosciski-Bosco');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jsmart8z', 'Balistreri, McClure and Gottlieb');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mdomelow90', 'Denesik-Smith');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smacdowal91', 'Kovacek-Orn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('arollins92', 'Hudson Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gmushawe93', 'Torphy-Schaefer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbottrill94', 'Davis-Koelpin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lprodrick95', 'Auer-Nolan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lmccann96', 'Lebsack and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sreichhardt97', 'Murphy Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('drevens98', 'Weissnat Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pitzkovwich99', 'Zulauf-Beatty');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gduckfield9a', 'Streich-Parker');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ckubyszek9b', 'Quitzon, Dietrich and Jenkins');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zkleuer9c', 'Bashirian-Shields');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('swillars9d', 'Gusikowski-Botsford');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahallworth9e', 'Monahan-Rowe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('chavvock9f', 'Stark LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('etschierse9g', 'Wisoky-Keeling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bmackowle9h', 'Zieme, Dicki and Lang');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('abasillon9i', 'Mraz-Grant');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ddamsell9j', 'Schowalter, Hettinger and Franecki');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdudill9k', 'Upton and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ydurante9l', 'Schamberger, Willms and Ebert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bpauleau9m', 'Keeling-Muller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('swinship9n', 'Schowalter, Schowalter and Hoeger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pfrisdick9o', 'Thompson and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ckerwick9p', 'Harvey, Oberbrunner and Becker');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdequesne9q', 'Boyle, Beatty and Lesch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mgoodison9r', 'Sanford and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adumpleton9s', 'Towne, Zulauf and Rolfson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cswendell9t', 'Stanton-Littel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bmuffen9u', 'Feest LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sconre9v', 'Breitenberg, Lemke and Lynch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hmcbrearty9w', 'Weissnat, O''Kon and Gutkowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sjeannenet9x', 'Davis LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('awalas9y', 'Spencer and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ipunter9z', 'Wilkinson-Little');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tgoskara0', 'Kihn, Grimes and Rau');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('abrumbiea1', 'Bruen-Hyatt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jhousbiea2', 'Bartell-Waters');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nzinckea3', 'Greenfelder-O''Keefe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bcosletta4', 'Howe, Kessler and Emmerich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('btivoliera5', 'Moore, Cartwright and Kihn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahorniga6', 'Hettinger, Collins and Mayert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hluebberta7', 'Marquardt LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ttenaunta8', 'Wiza-Kunde');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tfarrensa9', 'McLaughlin, Beahan and Williamson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dwashingtonaa', 'Kiehn Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('evillaab', 'Legros Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rjenynsac', 'Walter Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('odimitrovad', 'Parisian and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gkitchinae', 'Eichmann, Borer and Romaguera');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bclyneaf', 'Kuhic and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cgillottag', 'Kunde Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ktookillah', 'Shanahan, Jast and Schuppe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fcantillonai', 'Haag, Hane and Torp');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bneliusaj', 'Will Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wpokerak', 'Schroeder Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pconcannonal', 'Huel, Cremin and Gorczany');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jcraikam', 'Christiansen, Hegmann and Fritsch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('csherringhaman', 'Strosin, Upton and Anderson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lmcelweeao', 'Gislason-Herman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vmurrthumap', 'Williamson-Dietrich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gyakovichaq', 'Gleichner, Lubowitz and Lang');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('awhitfieldar', 'White, West and Bogan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gsalterneas', 'Blick Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ctoorat', 'Becker-Pfannerstill');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kwhightmanau', 'Jakubowski, Mosciski and Kirlin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('egrichukhinav', 'Bode, Pfeffer and Kihn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mklaessenaw', 'Hermann, Hand and Predovic');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmarqueseax', 'Rau LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('patteway', 'Gleason, Hintz and O''Kon');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('owakefieldaz', 'Emmerich, Rodriguez and Hessel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tmangeotb0', 'Monahan-Armstrong');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aharrisonb1', 'Deckow-Hintz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mcodringtonb2', 'Steuber-Bogisich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lhannisb3', 'Mohr-Raynor');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mcatonnetb4', 'Windler Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clinehamb5', 'Welch Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mmoreyb6', 'Muller Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tgeelanb7', 'Berge LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cfentyb8', 'Batz-Ratke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('halfordeb9', 'Volkman Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('yrobertsonba', 'Cummerata, Heathcote and Dach');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cparadycebb', 'Stracke Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ggaffneybc', 'Pfannerstill-Prohaska');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jrohfsenbd', 'Robel-Kling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rtregunnahbe', 'White-Stiedemann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dgilbanebf', 'Hintz-Treutel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jgoncalobg', 'Feeney-Hagenes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lchatelbh', 'Smith LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lsaizbi', 'Kub-Sporer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cgillisebj', 'Frami-Purdy');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sroderigobk', 'Daniel, Wiza and Jenkins');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lgudahybl', 'Keeling Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kleggittbm', 'Kling Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jruanebn', 'Schaden, Pagac and Labadie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tgiacopinibo', 'Nolan-Kshlerin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aclynmansbp', 'Walker-O''Keefe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pavrashinbq', 'Christiansen and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cbartosbr', 'Jakubowski-Parisian');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aroydsbs', 'Donnelly LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cboschbt', 'Barton-Emard');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zbrawleybu', 'Dietrich, Corkery and Gleason');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mtrembeybv', 'Crooks and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sbarkleybw', 'Heathcote-Wuckert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zhowsinbx', 'Haley, Anderson and Kutch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('atreadgallby', 'Hammes-Grimes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bpedreschibz', 'Nolan-Spinka');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mkirtlanc0', 'Sanford, Rolfson and Hintz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rpantryc1', 'Hettinger-Davis');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('amarac2', 'Crooks-Bernier');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cnancarrowc3', 'Macejkovic Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('plochranc4', 'Crona-Roberts');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('elawrencesonc5', 'Langosh Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('blansberryc6', 'Prosacco and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('icamblec7', 'Kreiger LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jcapelinc8', 'Hettinger, Bogisich and Hessel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adorsettc9', 'Lemke, Crist and Gulgowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gwaycottca', 'Roob and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nklavescb', 'Daniel Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pzecchetticc', 'Nader and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gdalycd', 'Little-Morar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mcozzice', 'Batz Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('limmscf', 'Koss-Bartell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('krasecg', 'Johnson-Tromp');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hsacherch', 'Marvin-Schaden');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ufereci', 'Hodkiewicz and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('obinnescj', 'Rogahn and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kraspelck', 'Dibbert and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('feuelscl', 'Boehm-Ernser');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('euphamcm', 'Abernathy, Schmitt and Bauch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kromeufcn', 'Dicki, Greenholt and Wiegand');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('barblasterco', 'Crist-Lebsack');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dmarshlandcp', 'Lebsack-Zboncak');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fjuliencq', 'Botsford-Yost');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('agrabbamcr', 'O''Reilly Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ggiblincs', 'Deckow-Skiles');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jfawderyct', 'Adams Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dpoppingcu', 'Schuppe and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmalloycv', 'Friesen and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('balwincw', 'Hane LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('okleinhausencx', 'Corkery-Oberbrunner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rvanhallecy', 'Crist, Adams and Rice');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('glawtiecz', 'Larson-McClure');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ckopped0', 'Spencer Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pmacterlaghd1', 'Mayer, Brekke and Bosco');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jdumigand2', 'Aufderhar Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('handrid3', 'Hauck, Littel and Altenwerth');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fherched4', 'Bednar, Schaefer and Christiansen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sarnauducd5', 'Rohan LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kmolsond6', 'Bogisich, Kuhn and Fahey');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rraitd7', 'Kshlerin and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adraayerd8', 'McKenzie LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ghubballd9', 'Zemlak, Heller and Terry');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cpeeverda', 'O''Hara, Orn and Huel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aofiellydb', 'Kautzer Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('greichartzdc', 'Johnston LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('istaresdd', 'Waelchi LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sgypsonde', 'Hessel-Mante');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sboordf', 'Hagenes, Zemlak and Zulauf');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('icrannadg', 'Nienow-Gislason');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mkonigdh', 'Crooks-Olson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('esuggatedi', 'Littel, Sanford and Lockman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bandreaccidj', 'Greenholt, Maggio and Wuckert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lherremadk', 'Raynor, Pfannerstill and Lynch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bglencrossdl', 'Ankunding and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gtraylendm', 'Heidenreich-Berge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('blubomirskidn', 'Boehm, Greenholt and Mayert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbellhousedo', 'Goldner-Friesen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dfrostdykedp', 'Smith LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('brubkedq', 'Batz-Wilkinson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rsessunsdr', 'Mayert Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('atriebnerds', 'Kertzmann, Howell and Powlowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bdurtnaldt', 'Dickinson-Reichel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fhickforddu', 'Wilderman, Lesch and Dickens');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jturnbulldv', 'Block Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sarmittdw', 'Howe-Hauck');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mgoodlifedx', 'Rice-Upton');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmulderdy', 'Howe Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wellershawdz', 'Hermiston Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vmccritchiee0', 'Gutkowski, Lindgren and Keeling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fcrichleye1', 'Reilly Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tscotsbrooke2', 'Crooks-Beier');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fkarlsene3', 'Cummings-Conroy');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mkettlestringese4', 'Zemlak-Nikolaus');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aruffeye5', 'Kemmer Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mblaskee6', 'Huel, Macejkovic and Welch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('yfranscionie7', 'Sawayn, Schamberger and Berge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('klindenbluthe8', 'Cummerata, Bins and Ebert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cvanderspohre9', 'Pacocha, Windler and Dach');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dmillicanea', 'MacGyver, Wisoky and Leffler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vferencowiczeb', 'Price, Wisozk and Fadel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldunnawayec', 'Leuschke Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gdeekesed', 'Upton Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sgiorgielliee', 'Schimmel Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('edecarteretef', 'Smith-White');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cglowinskieg', 'Huels, Jones and Cartwright');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rterbruggeneh', 'Fisher-Kub');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zaizikovichei', 'Keebler, Haley and Jaskolski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pwhiteej', 'Jaskolski-Boehm');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aoldenek', 'Kuvalis-Gerlach');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('acaddellel', 'Hammes, Fay and Medhurst');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('irhysem', 'Cormier Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kleppingtonen', 'Kassulke, Emmerich and Ratke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dgoudardeo', 'Morar Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sbestarep', 'Monahan, Runolfsson and Wisoky');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ddonkersleyeq', 'Turcotte Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vtinkhamer', 'Hagenes LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bjordisones', 'Schimmel-Huel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lmishet', 'Lesch-Carter');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmcclunaghaneu', 'Auer and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('reppsonev', 'Mohr, Ratke and Ziemann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kmissenew', 'Breitenberg, Predovic and Zemlak');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mbrankleyex', 'Hamill, Tremblay and Rohan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('iwassey', 'Halvorson Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kladdsez', 'Hammes, Ritchie and Flatley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldunbarf0', 'Grimes-Monahan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zgoutf1', 'Lueilwitz-Hyatt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fjanawayf2', 'Farrell-Breitenberg');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pbamberf3', 'Jacobson and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('askerrettf4', 'Kohler-Leffler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('caddenbrookef5', 'Legros Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adillonf6', 'Nicolas-Goyette');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sbeardsallf7', 'Simonis, Hoeger and Crist');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmurpheyf8', 'Mayer LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tstoggellf9', 'Jacobs-Goodwin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hsideryfa', 'Howe, Harris and Mueller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bbruckenthalfb', 'Graham Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fhollymanfc', 'Robel LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bashbornefd', 'O''Reilly, Jacobson and Flatley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nmcnairfe', 'Streich Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('oschulkenff', 'Homenick, Stamm and Abernathy');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('icellierfg', 'Thiel Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('welixfh', 'Bashirian-Kuhic');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cslocumbfi', 'Price-Bayer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bstockingfj', 'Quigley Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cveelerfk', 'O''Kon Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gnoicefl', 'Terry Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gpllufm', 'Bernier, Berge and Ondricka');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wabelefn', 'Streich-Okuneva');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fdosdillfo', 'Hirthe Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmaccathayfp', 'Hills and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('imastersonfq', 'Smitham, Wintheiser and Casper');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('agerriefr', 'Turner, Hahn and Lueilwitz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ayoudellfs', 'Braun, Stiedemann and Connelly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jtethcoteft', 'Casper Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ccottisfu', 'Walker-Beatty');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bscrivenorfv', 'Terry Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mcornwellfw', 'Lang-Ankunding');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ubrawnfx', 'Cummings, Hackett and Greenholt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bhandrekfy', 'Hayes-Carroll');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jdiniscofz', 'Spinka LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rguyeg0', 'Hyatt Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cpresserg1', 'Lubowitz, Kuhlman and Conn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rtreppasg2', 'Robel-Fisher');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('icreavang3', 'Hyatt-Dicki');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gkeffordg4', 'Bruen Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gbroadfieldg5', 'Gutmann-Lowe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bstickinsg6', 'Sawayn, Osinski and Kutch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bcastellang7', 'Greenfelder-Gutmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hparslowg8', 'Rodriguez and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dleregog9', 'MacGyver and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ndrioliga', 'Kuhlman, White and Nienow');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pjenkersongb', 'Wuckert Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gwestovergc', 'Beier and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kkleinmintzgd', 'Boehm-Metz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dtommasige', 'Legros Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ccrambiegf', 'Hilpert Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ngirkingg', 'Romaguera-Schuster');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pwithamgh', 'Corkery Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mblaaschgi', 'VonRueden LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bmcquilliamgj', 'Hayes Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mmiroygk', 'DuBuque, Dietrich and Bashirian');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rhorickgl', 'Predovic Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fblundengm', 'Fadel, Baumbach and Berge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bcawgn', 'Glover, Ratke and Morissette');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('spiffgo', 'Grady-Kuhn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbrimfieldgp', 'Homenick, Cassin and Friesen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clesleygq', 'Trantow, Bahringer and Ward');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ngwillyamgr', 'Crona-Grimes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kloadegs', 'Barton, Bode and Zieme');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mwishartgt', 'Emard-Bechtelar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adawsongu', 'Sanford Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kspirrittgv', 'Hauck LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('acrottaghgw', 'Roberts Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nnelmgx', 'Schuppe-Doyle');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gfleygy', 'Hansen and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wcurtissgz', 'MacGyver-Berge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldunckleyh0', 'Dietrich-Balistreri');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fallredh1', 'Veum, Herman and Friesen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rocannovaneh2', 'Douglas, Harber and Zulauf');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jwharfeh3', 'Howell, Trantow and Hudson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ascanterburyh4', 'Keeling, Rohan and Osinski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('merth5', 'Jakubowski, Kshlerin and Powlowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rstiddardh6', 'Bartoletti-Kunde');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kswinfonh7', 'Green, Wilkinson and Lowe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hronaldsonh8', 'Walter-Larson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nchillistoneh9', 'Considine and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ainghamha', 'Mraz and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ckleinthb', 'Bogisich LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ascothornhc', 'Heaney Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jsoltanhd', 'Satterfield-Hilpert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('icallamhe', 'Zieme-Pagac');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lberghf', 'Bayer-Reichert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wrennleshg', 'Dibbert-McKenzie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zdoddshh', 'Altenwerth and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hjayshi', 'Parisian and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbeurichhj', 'King-DuBuque');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aenokssonhk', 'Gulgowski-Boyer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kwebbornhl', 'Schamberger, Luettgen and Williamson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lolliffhm', 'Cole LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kharesignhn', 'Hoppe-West');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rsmaileho', 'Simonis, Labadie and Kshlerin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('llydsterhp', 'Wuckert-Ritchie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('krevillehq', 'Wiegand-Price');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ghuckelhr', 'Hintz, Cassin and Aufderhar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mtregiddohs', 'Kutch and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lroomesht', 'Mitchell Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ptuffellhu', 'Hartmann and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('priplyhv', 'Witting, Crooks and Adams');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('grorkehw', 'Homenick, Macejkovic and Stehr');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('egribbinshx', 'Pollich-Wunsch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('emacgallhy', 'Lakin, Botsford and Cartwright');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahammentshz', 'Rodriguez, Kihn and Torp');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lcostelloei0', 'Mayer, Stamm and Muller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vculberti1', 'Bernhard LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kceeleyi2', 'Maggio-Sporer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('stileri3', 'Fahey-Gutmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sdissmani4', 'Powlowski-Zulauf');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('loliphanti5', 'Thompson, Streich and Lind');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cambleri6', 'Howell-Hegmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sfinnisi7', 'Walsh, Gutkowski and Weimann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mchellami8', 'Schiller-Denesik');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hbrometi9', 'Mueller, Halvorson and Prohaska');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmioniia', 'Beatty-Jacobi');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('khumblestoneib', 'Glover LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smatthiusic', 'Bernier, Murazik and Herzog');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('iblabieid', 'Greenholt, Feeney and Blick');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ngadsdenie', 'Williamson, McKenzie and Gerhold');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ghastingsif', 'Cremin and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adevasig', 'Marvin LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bsainerih', 'Gibson, Hauck and Schulist');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gallabartonii', 'Goodwin, Rogahn and Friesen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wmckibbinij', 'Hoeger and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vcorneliussenik', 'Hills Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('slorraineil', 'Littel, Mante and Kemmer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('agrundyim', 'Dibbert-Lemke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hbroodesin', 'Keebler, Lakin and Haag');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cnairneio', 'Stanton, Balistreri and Moore');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pritmeierip', 'Reichel-Jast');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ggaspariq', 'Wiza Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdeveyir', 'Price, Schuppe and Hagenes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tfunnellis', 'Kunze-Von');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tcardenosait', 'Daugherty, Bergstrom and Armstrong');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('grubinekiu', 'Hyatt and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cgarmstoniv', 'Frami Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sfeeiw', 'Marvin-Hilpert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ecatanheiraix', 'Runolfsson LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('friddiy', 'Hills-Runolfsdottir');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dbourgourdiz', 'Predovic-Muller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nocrottyj0', 'Daniel Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rkymej1', 'Hessel-Casper');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('troftj2', 'Schneider-Heller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('yaddlestonej3', 'Christiansen, Hermiston and Ernser');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nstrobandj4', 'Bednar, Grimes and Williamson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('snairnsj5', 'Douglas, Tremblay and Fay');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ccawleyj6', 'Bernier-Frami');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('doffaj7', 'Feeney and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vburrilj8', 'Shields Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('edearnlyj9', 'Stiedemann, Williamson and Yundt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rcamilioja', 'Doyle-Huels');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rswalwelljb', 'Bartoletti-Langosh');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jjedraszekjc', 'Quigley Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jsivierjd', 'Gibson Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('baskeyje', 'Ondricka and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('otupperjf', 'Ruecker-Blick');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ericcijg', 'Larson-Cremin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ewillavoysjh', 'Trantow, Schuster and Kub');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eaddsji', 'Mante-Bins');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmoffettjj', 'Koss LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dglendiningjk', 'Jacobs, Wolf and Wunsch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rlytelljl', 'Olson, Buckridge and Quigley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ddreusjm', 'Kautzer-Pouros');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lgentryjn', 'Connelly-Bernhard');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gneilsonjo', 'Larkin, Lind and Hamill');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dlithcowjp', 'Welch-Daniel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gemansonjq', 'Shanahan, Robel and Lesch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('frozierjr', 'Senger, Wehner and Waelchi');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kgavenjs', 'Crona, Mitchell and Rau');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bdengeljt', 'DuBuque Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdeverellju', 'O''Conner, Conroy and Harvey');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jhawkwoodjv', 'Dooley, Brakus and Berge');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dmcsherryjw', 'Hackett and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('acurlingjx', 'Schamberger, Kilback and Shanahan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aheapsjy', 'Kulas LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('olackyjz', 'Mosciski, Bosco and Fritsch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldarringtonk0', 'Emmerich, Heaney and Labadie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lstitfallk1', 'Metz-Fadel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bjevesk2', 'Schamberger-Hilpert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gterrenk3', 'Ankunding Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahoytk4', 'Paucek Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jrigebyk5', 'Zieme LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('imathivetk6', 'White Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bdanserk7', 'Mosciski, Lind and Reynolds');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ksturmank8', 'Lang, Medhurst and Pfannerstill');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eohallorank9', 'Johnson-Schamberger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdeinhardka', 'Quigley, Smitham and Walsh');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ibrakerkb', 'Haley, Kihn and Erdman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('preboulkc', 'Turcotte-Blanda');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('abuntinkd', 'Romaguera-Rolfson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eduhamke', 'Langosh, VonRueden and Gutmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mdecastelainkf', 'Bergnaum, Muller and Kessler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('btwinningkg', 'Turner Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lfilyakovkh', 'Bartoletti LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dlemeryki', 'Marvin and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aparemankj', 'Schamberger-Kunze');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tgodbeherekk', 'Luettgen-Stark');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clymbournekl', 'Walter, Willms and Quigley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fpopworthkm', 'Homenick, Schulist and Jones');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ibanischkn', 'Langosh LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('srigdenko', 'Considine, Mitchell and Deckow');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mholdrenkp', 'Lockman, Runte and Koch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ascutchingskq', 'Reinger, Stamm and Schmidt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dwhitfordkr', 'Smith Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bruskeks', 'Gleason-Gutmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('spitcockkt', 'Auer and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('emeahku', 'Ernser-Brekke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jtyttertonkv', 'Macejkovic, Lowe and Hamill');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mellifkw', 'Ratke, Langworth and O''Reilly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ballawaykx', 'Brakus and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jcasterouky', 'Effertz-Cummerata');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tlockartkz', 'Parisian LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cschreursl0', 'Marvin, Dickinson and Kshlerin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mpatronl1', 'Block Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('shanselll2', 'Gislason, Jenkins and Tromp');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('oleneyl3', 'Bayer Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fvinckl4', 'Wunsch-Hegmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dgingell5', 'Bashirian, Homenick and Mayert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('qrubertellil6', 'Nicolas Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rkemel7', 'Howe and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ltwyningl8', 'Rath, Strosin and Schumm');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sbegbiel9', 'Quigley-Fay');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dadamla', 'Weissnat-Jenkins');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ftrevorrowlb', 'Sawayn-Stoltenberg');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('djennawaylc', 'Johnson, Cruickshank and Keeling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lantillld', 'Klein-Rice');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dheynenle', 'Crona, Runolfsdottir and Volkman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbrownsilllf', 'Roberts-Kling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmcneicelg', 'Dickinson-Koch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('asallinglh', 'Leuschke, Lemke and Mosciski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('xsimonuttili', 'Ryan, Goodwin and Dietrich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ghendrickslj', 'Murazik Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gweblandlk', 'Emard, Fay and Orn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('awankelll', 'Orn, Lebsack and Rath');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aspiaggialm', 'Trantow Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmaseresln', 'Lehner, Hegmann and Mohr');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jdowleylo', 'Oberbrunner, Koss and Oberbrunner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('crowleylp', 'Crooks-Bartell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahawkyenslq', 'Dickinson, Rodriguez and Crooks');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('alamkinlr', 'Pacocha Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mminerls', 'Parisian and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('truprechterlt', 'Bayer LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sforthlu', 'Reichert, Kunde and Bogan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rlabblv', 'Gorczany Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmerrelllw', 'Klein, Conn and Veum');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cannearlx', 'Walsh, Dibbert and Jakubowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('abickmorely', 'Smith-Lesch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lpaiklz', 'Reynolds, Jacobson and Stanton');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jisakovm0', 'Nitzsche, Balistreri and Deckow');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aduffiem1', 'Upton-Medhurst');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fbestmanm2', 'Klocko-Fritsch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hlindenboimm3', 'Fay and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clukerm4', 'Wuckert, Schmidt and Adams');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tlinnockm5', 'Reinger-Effertz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lgirodierm6', 'Torp-Hahn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rwindebankm7', 'Corwin-Dibbert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cverrillm8', 'Rodriguez, Keebler and Shields');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('stullethm9', 'Wilkinson-Lakin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bmatissema', 'Schaefer-Bernhard');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kbastidemb', 'Gleason-Halvorson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('blormanmc', 'Reichel Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pdagostinimd', 'Jones-Cassin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tanwylme', 'Kreiger and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ltantmf', 'Maggio, Purdy and Zemlak');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wodonohuemg', 'Spencer-Rath');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('astalleymh', 'Graham, Schumm and Rogahn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('blangmanmi', 'Goodwin, Nitzsche and Hammes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rjanwaymj', 'Ortiz, Hickle and Schuster');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sgeindremk', 'Abbott-Keeling');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mkleselml', 'Nicolas, Stroman and Emmerich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zpoxsonmm', 'Hayes, Smith and Schultz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kwickhammn', 'Wyman Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aordemannmo', 'Adams, Marks and Purdy');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ekilgrewmp', 'Bashirian and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rdurkinmq', 'Farrell-Hodkiewicz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kvayromr', 'Walker-Stiedemann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mnicholasms', 'Oberbrunner, Cummerata and Robel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ebrewinmt', 'Bogisich-Schumm');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbradberrymu', 'Hettinger, Kris and Morissette');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pmcwhirtermv', 'Lueilwitz, Schultz and Keebler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wsitlintonmw', 'Veum Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mnormanellmx', 'Goldner-Terry');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hhammersleymy', 'McGlynn-Becker');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('omcsperronmz', 'Stamm, Feeney and Jaskolski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fcorstann0', 'Bernhard-Hermiston');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kjozwikn1', 'Runolfsson, Weber and Swaniawski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cbruinsn2', 'Bradtke, Murazik and Ward');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fsalzburgern3', 'Brakus, Fisher and Orn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tsheeresn4', 'Crist-Cremin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pclinesn5', 'Kerluke-Cummerata');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdulantyn6', 'Hills-Connelly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bwickhamn7', 'Gleason and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbarnsdalen8', 'Brekke, Carter and Rowe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pblazyn9', 'Bahringer, Collier and Goyette');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kreedena', 'Greenfelder-Hoppe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('drobardeynb', 'Towne-Legros');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lrickerseync', 'Cole Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lcisecnd', 'Shanahan Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('efidgene', 'Reinger Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dleithharveynf', 'Hahn-Schmidt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ecolumng', 'Mayert, Kunde and Champlin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ccoomernh', 'Flatley-Erdman');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hllorensni', 'Crooks Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ldavidovicnj', 'Rau, Bruen and Cremin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jwhitlandnk', 'Parisian and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('xbodmannl', 'Carroll, Schowalter and Ruecker');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdickensonnm', 'Cruickshank, Torphy and Walker');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tmoulsdalenn', 'Williamson-Bartell');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mstintonno', 'Bradtke, Brakus and Kovacek');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('atollettnp', 'Padberg Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rfrainnq', 'Flatley Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('margentenr', 'Mayert LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ofinneyns', 'Hilll and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fsimonetonnt', 'Mertz LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fhugonu', 'Turner, Metz and Boehm');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ashadracknv', 'Weimann, Prosacco and Morar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('roakshottnw', 'Lubowitz and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aspringthorpenx', 'Gottlieb, Klocko and Ernser');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rduplantierny', 'Feest and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('agoodfellowenz', 'Lakin, Reilly and Swift');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aelsipo0', 'Jerde, Fay and Rohan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('edaneleto1', 'Douglas LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jsaundero2', 'Barton-Rolfson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hcarso3', 'Kulas, Thompson and Kunze');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pgouldthorpeo4', 'Jacobi-Ondricka');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('erutero5', 'Bergnaum Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mducarneo6', 'Powlowski, Champlin and Wolff');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('epicardo7', 'Haley-Schmeler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mproskeo8', 'Weber-Aufderhar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wshurlocko9', 'Stehr-Hartmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('geunsonoa', 'Ritchie-Halvorson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lkopmanob', 'Dickinson, Barton and Shanahan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('iansticeoc', 'Littel, Cole and Reilly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smcgurkod', 'Hoeger Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mkennadyoe', 'Goyette LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mmccutcheonof', 'Mann-Waelchi');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zusbornog', 'Walsh-Dibbert');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dwycheoh', 'McDermott Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gflynnoi', 'Bailey, Von and Okuneva');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dpassyoj', 'Bailey-Wilkinson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hswindellok', 'Shields, Lemke and Zieme');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rwhitloeol', 'Monahan, Kilback and McKenzie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cwethersom', 'Nikolaus and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('scogleyon', 'Kunze, Fadel and Klein');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tstrahanoo', 'Zulauf-McKenzie');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('alandop', 'Walker-Doyle');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('galywinoq', 'McKenzie-Kulas');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gtaintonor', 'Hoeger and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rstormontos', 'Schowalter-Feest');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vzelakeot', 'Balistreri-Nicolas');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rcobbeou', 'Daniel LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aalmanov', 'Skiles-Schimmel');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nbrewardow', 'Walsh-Hodkiewicz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bemmanuelox', 'Cartwright-Johnston');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('agylesoy', 'Swaniawski, Wuckert and Pfeffer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nshrieveoz', 'Kozey-Kuhic');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('phubbersteyp0', 'Brown and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('alorkingp1', 'Schaefer and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gdellop2', 'Legros, Senger and O''Conner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('loldcotep3', 'Dickinson-Bernier');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wgilletp4', 'Ankunding Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('sbaglowp5', 'Beier-Sipes');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mwhorfp6', 'Bode-Watsica');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adiamentp7', 'Ankunding-Gaylord');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eabramovp8', 'Torphy-Yundt');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dfewingsp9', 'Hodkiewicz-Runolfsson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rgeaneypa', 'DuBuque, Hilll and Aufderhar');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dforestallpb', 'Wehner, Emard and Cartwright');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ndumberellpc', 'Rogahn LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('smattheispd', 'Klein, Mann and Cartwright');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aezzype', 'Renner, Heller and Schroeder');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aspikingspf', 'Goldner Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mtixallpg', 'Hand LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mbeilbyph', 'Wuckert-O''Reilly');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ltongspi', 'Leuschke, Kulas and Hoeger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('vtomblettpj', 'Hickle-Dare');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('castonpk', 'Thiel Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mbarraspl', 'Kunde and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jmchardypm', 'Feil, Mante and Kirlin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('kfayermanpn', 'Larson, Crona and Mante');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ahounsonpo', 'Ziemann-Durgan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('zsnaselpp', 'Kertzmann Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cfostenpq', 'Kiehn, Toy and Gutkowski');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rapdellpr', 'Cassin Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gmurisps', 'Schneider, Osinski and Brown');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hlongegapt', 'Weber and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdivineypu', 'Rath-Medhurst');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('asandiferpv', 'Beer Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('adowearspw', 'Leuschke, Sporer and Crooks');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hyankishinpx', 'Champlin, Doyle and Morissette');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('scrocepy', 'Mohr and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ikemmonspz', 'Kuphal-Pacocha');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rbyasq0', 'Kunde-Williamson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wmacgianyq1', 'Spencer, Lemke and Miller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wraithbyq2', 'Wisozk, Vandervort and Lemke');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('clubertoq3', 'Rohan Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('scalvenq4', 'Ruecker, Lang and Pfannerstill');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('gpaddyq5', 'Ankunding, Ortiz and Kreiger');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dpenniellq6', 'Wisozk-Carroll');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('landererq7', 'McKenzie LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('klinsteadq8', 'Crist LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hgliddonq9', 'Schuster LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('plambdinqa', 'Marvin-Flatley');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rrutgersqb', 'Runolfsdottir-Kunde');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jhamssonqc', 'Rosenbaum-Homenick');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('aollingtonqd', 'Feeney-Mueller');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bstenbridgeqe', 'Fadel Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lrowselqf', 'Beatty, Flatley and Thompson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('truthenqg', 'Block LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tferyqh', 'Osinski, Gottlieb and Wiegand');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mstadenqi', 'Sipes, McLaughlin and Orn');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nmcgrudderqj', 'Haag, Bauch and Johnston');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lmegroffqk', 'Wintheiser, Lehner and Lueilwitz');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mraithbyql', 'Hackett and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('hpleadenqm', 'Adams, Tromp and Streich');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nglydeqn', 'Beahan LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cmallenqo', 'Herzog-Padberg');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cklimentqp', 'Waters-Waters');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rrosencwaigqq', 'Gibson and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cvassbenderqr', 'Powlowski, Effertz and Hartmann');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('pmurreyqs', 'Hoeger-Mayer');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wgheeraertqt', 'Adams, Pacocha and Roberts');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('wkilgrewqu', 'Will-Kohler');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ashackleqv', 'Mohr Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tyakoboviczqw', 'Gislason, Larson and Rohan');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ebentoqx', 'Emard Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jolliarqy', 'Sanford, Thompson and Schowalter');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ndullinghamqz', 'Kertzmann, Pacocha and Hirthe');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('fsketchr0', 'O''Hara Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mbambrughr1', 'Kihn LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mmackisonr2', 'Crist, Mante and King');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mpendergastr3', 'Macejkovic, Fay and Upton');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ksauntonr4', 'Terry and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('ecrookr5', 'Feest LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('onorthallr6', 'Watsica-Runolfsson');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cashingdenr7', 'Kling LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('tbrownleer8', 'Champlin Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('eferrieresr9', 'Toy LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jratnagera', 'Gutmann, Flatley and Huels');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('nhobsonrb', 'Willms Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('bstrainrc', 'Larson-Wehner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rtavnerrd', 'Pfannerstill-Marvin');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('owaleworkre', 'Fadel and Sons');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mtreneerrf', 'Watsica LLC');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('rsaphrg', 'McDermott-Graham');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jnelthorprh', 'Ryan, Marvin and Welch');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('corganri', 'Lesch-Goldner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jreilyrj', 'Von-Johns');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dgreenshielsrk', 'Littel, Schaefer and Schoen');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('mtotherrl', 'Kulas, Rippin and Pacocha');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('acurnnokrm', 'Wiza Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('cdurrancern', 'Hirthe, Sawayn and Altenwerth');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('spapachristophorouro', 'Schmidt Inc');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('dclaysonrp', 'Beahan-Schinner');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('jdominguesrq', 'Orn Group');
insert into CLUB_MEMBERS (CMUsername, CMClub_name) values ('lmunceyrr', 'Mann, Okuneva and Lockman');
